version: '3'
services:
  jenkins:
    container_name: jenkins
    image: jenkins/docker
    build:
      context: .
    user: root
    ports:
      - "8999:8080"
      - "8443:8443"
      - "50000:50000"
    restart: always
    volumes:
         - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - net
networks:
  net: